environment: dev
image:
  tag: develop
  pullPolicy: IfNotPresent
  pullSecret: "default"
  repository: "will-be-overridden-by-set"
service:
  type: ClusterIP
  port: 80
  nodePort: 8002
replicaCount: 1
serviceAccount:
  create: false
ingress:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false
django:
  debug: "True"
  allowedHosts: "*"