name: "Task 1: Terraform CI/CD"

# Запуск конвеєра при пуші в гілку task1 або вручну
on:
  push:
    branches:
      - main
    paths:
      - 'task1/**'
  workflow_dispatch:

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest

    # Налаштування робочої директорії, як вимагає екзамен для task1
    defaults:
      run:
        working-directory: ./task1

    # Завантаження секретів із GitHub
    env:
      TF_VAR_do_token: ${{ secrets.DO_PAT }}
      TF_VAR_spaces_access_id: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      TF_VAR_root_password: ${{ vars.ROOT_PASSWORD }}
      # Ці дві змінні обов'язкові для модуля S3 (який працює з DO Spaces)
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # Виконання перевірки перед розгортанням
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Виконання розгортання лише якщо Terraform Plan пройшов успішно
      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
